=== JuanluOnieva/BBTrack/xml-xsl/Medicos/XSDMedico.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns=""
elementFormDefault="qualified">
<xs:element name="bbTrack">
  <xs:complexType>
    <xs:sequence>
		<xs:element name="Medico">
				<xs:complexType>
				<xs:sequence>
						<xs:attribute name="Licencia" type="xs:string" use="required"/>
		  			<xs:element name="Nombre" type="xs:string" use="required"/>
		  				<xs:simpleType>
						    <xs:restriction base="xs:string">
							    <xs:length value="45"/>
						    </xs:restriction>
						 </xs:simpleType>
			      	<xs:element name="Apellidos" type="xs:string" use="required"/>
			      		<xs:simpleType>
						    <xs:restriction base="xs:string">
							    <xs:length value="45"/>
							    <xs:whiteSpace value="preserve"/>
						    </xs:restriction>
						 </xs:simpleType>
			      	<xs:element name="Sexo" type="xs:string" use="required"/>
			      		<xs:simpleType>
							  <xs:restriction base="xs:string">
									<xs:pattern value="Hombre|Mujer"/>
						      </xs:restriction>
							  </xs:simpleType>
			      	<xs:element name="Especialidad" type="xs:string" use="required"/>
			      		<xs:simpleType>
					    	<xs:restriction base="xs:string">
					      		<xs:length value="45"/>
					    	</xs:restriction>
					  	 </xs:simpleType>
					<xs:element name="Consultas">
							<xs:complexType>
							<xs:sequence>
									<xs:element name="idConsulta" type="xs:string" use="required"/>
								</xs:sequence>
							</xs:complexType>
				</xs:sequence>
				</xs:complexType>
		</xs:element>
	</xs:sequence>
  </xs:complexType>
</xs:element>

=== JuanluOnieva/BBTrack/xml-xsl/Medicos/M-23444.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLMedico.xsl"?>
<bbTrack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSDMedico.xsd">
		<Medico Licencia="M-23444">
			<Nombre>Miguel</Nombre>
			<Apellidos>Perez Jimenez</Apellidos>
			<Sexo>Hombre</Sexo>
			<Especialidad>Ginecologia</Especialidad>
			<Consultas>
				<idConsulta>2-02-HC</idConsulta>
			</Consultas>
		</Medico>
</bbTrack>

=== JuanluOnieva/BBTrack/prTableToXML/IS/Medicos/M-23494.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLMedico.xsl"?>
<bbTrack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSDMedico.xsd">
		<Medico Licencia="M-23494">
			<Nombre>Lucia</Nombre>
			<Apellidos>Toscano Varela</Apellidos>
			<Sexo>Mujer</Sexo>
			<Especialidad>Obstetra</Especialidad>
			<Consultas>
				<idConsulta>2-09-HCH</idConsulta>
			</Consultas>
		</Medico>
</bbTrack>

=== JuanluOnieva/BBTrack/prTableToXML/IS/Medicos/M-99432.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLMedico.xsl"?>
<bbTrack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSDMedico.xsd">
		<Medico Licencia="M-99432">
			<Nombre>Maria</Nombre>
			<Apellidos>Pastor Smith</Apellidos>
			<Sexo>Mujer</Sexo>
			<Especialidad>Urgencias</Especialidad>
			<Consultas>
				<idConsulta>1-32-HCH</idConsulta>
			</Consultas>
		</Medico>
</bbTrack>

=== JuanluOnieva/BBTrack/API-python/static/download/bbTrack/Medicos/M-10938.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XSLMedico.xsl"?>
<bbTrack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDMedico.xsd">
		<Medico Licencia="M-10938">
			<Nombre>Antonio</Nombre>
			<Apellidos>Jurado Martos</Apellidos>
			<Sexo>Hombre</Sexo>
			<Especialidad>Urgencias</Especialidad>
			<Consultas>
				<idConsulta>1-22-HC</idConsulta>
			</Consultas>
		</Medico>
</bbTrack>

=== JuanluOnieva/BBTrack/prTableToXML/IS/Medicos/M-98488.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLMedico.xsl"?>
<bbTrack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSDMedico.xsd">
		<Medico Licencia="M-98488">
			<Nombre>Juan</Nombre>
			<Apellidos>Serrano Lopez</Apellidos>
			<Sexo>Hombre</Sexo>
			<Especialidad>Obstetra</Especialidad>
			<Consultas>
				<idConsulta>2-02-HC</idConsulta>
			</Consultas>
		</Medico>
</bbTrack>
